### ISSUE TITLE
Editor not working

### ISSUE THREAD

**Issue by stubear** [fruitstudios/AviaryImageEditor#2]
Tried the plugin this afternoon but was unable to get the editor to work. All I see is a loading spinner on the editor icons when I click them and occasionally I get a loading spinner on the image itself. This was on a local dev site and tested with the latest versions of Chrome and Safari on Yosemite. I also tried both API keys Adobe created.

**Comment by stubear** [comment]
Problem solved. I had not enabled CORS.

**Comment by samhibberd** [comment]
Ah, we did have some strange issues when testing with the local version's early on.

Thanks for letting us know.

**Comment by samcorney** [comment]
Nice spot here. As Sam says above we did indeed run into some very similar issues when testing this initially locally. I've made a tweak to the readme to help anyone who might come across the same situation again in the future!
